/// <reference types="vite/client" />

// `virtual:pwa-register` is generated by vite-plugin-pwa at build time, so
// TypeScript has no file to resolve it from without this. See UpdatePrompt.tsx.
/// <reference types="vite-plugin-pwa/client" />
